# Generated by Django 3.2.12 on 2023-09-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20230918_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
