# Generated by Django 3.2.12 on 2023-09-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
