# Generated by Django 3.2.12 on 2023-09-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagenes',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
    ]
